# -----------------------------------------------------------------------------
# Plugin List
# -----------------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'

# -----------------------------------------------------------------------------
# Resurrect & Continuum Configuration
# -----------------------------------------------------------------------------
set -g @continuum-restore 'on'                    # Automatically restore sessions on tmux start
set -g @continuum-save-interval '120'             # Save sessions every 2 hours
set -g @resurrect-capture-pane-contents 'on'      # Restore pane contents
set -g @resurrect-strategy-nvim 'session'         # Restore nvim sessions if using vim-obsession

# -----------------------------------------------------------------------------
# Global Configuration
# -----------------------------------------------------------------------------
set -g default-terminal "tmux-256color"  # Use 256-color terminal
set -g base-index 1                     # Start window numbering at 1
set -g pane-base-index 1                # Start pane numbering at 1
set -g mouse on                         # Enable mouse support
set -g status-position top              # Status bar at the top
set -g renumber-windows on              # renumber all windows when any window is closed

# -----------------------------------------------------------------------------
# Tokyo Night Theme Configuration
# -----------------------------------------------------------------------------
source-file ~/.config/tmux/tokyonight_night.tmux

# -----------------------------------------------------------------------------
# Key Bindings
# -----------------------------------------------------------------------------
bind-key -r r source-file ~/.config/tmux/tmux.conf       # Reload tmux configuration
set -g prefix C-a                                        # Change prefix to Ctrl-a
unbind C-b                                               # Unbind default prefix (Ctrl-b)
bind '"' split-window -c "#{pane_current_path}"          # Set current path when split window
bind % split-window -h -c "#{pane_current_path}"         # Set current path when split window
bind c new-window -c "#{pane_current_path}"              # Set current path when split window
bind z resize-pane -Z                                    # Maximize pane

# -----------------------------------------------------------------------------
# SessionX Key Bindings
# -----------------------------------------------------------------------------
set -g @sessionx-bind 's'
bind-key S command-prompt -p "New Session:" "new-session -t '%%'"  # Create new session
bind-key K confirm kill-session                                    # Kill session with confirmation

# -----------------------------------------------------------------------------
# Initialize TMUX Plugin Manager
# -----------------------------------------------------------------------------
run '~/.config/tmux/plugins/tpm/tpm'  # Keep this line at the very bottom
unbind-key C-s                        # Disable tmux-resurrect manual save
unbind-key C-S                        # Disable tmux-resurrect manual save for extended-key terminals
